/*Autogenerated index*/

import ThreeDRotationIcon from "./icons/3d_rotation.js";
import AcUnitIcon from "./icons/ac_unit.js";
import AccessAlarmIcon from "./icons/access_alarm.js";
import AccessAlarmsIcon from "./icons/access_alarms.js";
import AccessTimeIcon from "./icons/access_time.js";
import AccessibilityIcon from "./icons/accessibility.js";
import AccessibleIcon from "./icons/accessible.js";
import AccountBalanceIcon from "./icons/account_balance.js";
import AccountBalanceWalletIcon from "./icons/account_balance_wallet.js";
import AccountBoxIcon from "./icons/account_box.js";
import AccountCircleIcon from "./icons/account_circle.js";
import AdbIcon from "./icons/adb.js";
import AddIcon from "./icons/add.js";
import AddAPhotoIcon from "./icons/add_a_photo.js";
import AddAlarmIcon from "./icons/add_alarm.js";
import AddAlertIcon from "./icons/add_alert.js";
import AddBoxIcon from "./icons/add_box.js";
import AddCircleIcon from "./icons/add_circle.js";
import AddCircleOutlineIcon from "./icons/add_circle_outline.js";
import AddLocationIcon from "./icons/add_location.js";
import AddShoppingCartIcon from "./icons/add_shopping_cart.js";
import AddToPhotosIcon from "./icons/add_to_photos.js";
import AddToQueueIcon from "./icons/add_to_queue.js";
import AdjustIcon from "./icons/adjust.js";
import AirlineSeatFlatIcon from "./icons/airline_seat_flat.js";
import AirlineSeatFlatAngledIcon from "./icons/airline_seat_flat_angled.js";
import AirlineSeatIndividualSuiteIcon from "./icons/airline_seat_individual_suite.js";
import AirlineSeatLegroomExtraIcon from "./icons/airline_seat_legroom_extra.js";
import AirlineSeatLegroomNormalIcon from "./icons/airline_seat_legroom_normal.js";
import AirlineSeatLegroomReducedIcon from "./icons/airline_seat_legroom_reduced.js";
import AirlineSeatReclineExtraIcon from "./icons/airline_seat_recline_extra.js";
import AirlineSeatReclineNormalIcon from "./icons/airline_seat_recline_normal.js";
import AirplanemodeActiveIcon from "./icons/airplanemode_active.js";
import AirplanemodeInactiveIcon from "./icons/airplanemode_inactive.js";
import AirplayIcon from "./icons/airplay.js";
import AirportShuttleIcon from "./icons/airport_shuttle.js";
import AlarmIcon from "./icons/alarm.js";
import AlarmAddIcon from "./icons/alarm_add.js";
import AlarmOffIcon from "./icons/alarm_off.js";
import AlarmOnIcon from "./icons/alarm_on.js";
import AlbumIcon from "./icons/album.js";
import AllInclusiveIcon from "./icons/all_inclusive.js";
import AllOutIcon from "./icons/all_out.js";
import AndroidIcon from "./icons/android.js";
import AnnouncementIcon from "./icons/announcement.js";
import AppsIcon from "./icons/apps.js";
import ArchiveIcon from "./icons/archive.js";
import ArrowBackIcon from "./icons/arrow_back.js";
import ArrowDownwardIcon from "./icons/arrow_downward.js";
import ArrowDropDownIcon from "./icons/arrow_drop_down.js";
import ArrowDropDownCircleIcon from "./icons/arrow_drop_down_circle.js";
import ArrowDropUpIcon from "./icons/arrow_drop_up.js";
import ArrowForwardIcon from "./icons/arrow_forward.js";
import ArrowUpwardIcon from "./icons/arrow_upward.js";
import ArtTrackIcon from "./icons/art_track.js";
import AspectRatioIcon from "./icons/aspect_ratio.js";
import AssessmentIcon from "./icons/assessment.js";
import AssignmentIcon from "./icons/assignment.js";
import AssignmentIndIcon from "./icons/assignment_ind.js";
import AssignmentLateIcon from "./icons/assignment_late.js";
import AssignmentReturnIcon from "./icons/assignment_return.js";
import AssignmentReturnedIcon from "./icons/assignment_returned.js";
import AssignmentTurnedInIcon from "./icons/assignment_turned_in.js";
import AssistantIcon from "./icons/assistant.js";
import AssistantPhotoIcon from "./icons/assistant_photo.js";
import AttachFileIcon from "./icons/attach_file.js";
import AttachMoneyIcon from "./icons/attach_money.js";
import AttachmentIcon from "./icons/attachment.js";
import AudiotrackIcon from "./icons/audiotrack.js";
import AutorenewIcon from "./icons/autorenew.js";
import AvTimerIcon from "./icons/av_timer.js";
import BackspaceIcon from "./icons/backspace.js";
import BackupIcon from "./icons/backup.js";
import Battery20Icon from "./icons/battery_20.js";
import Battery30Icon from "./icons/battery_30.js";
import Battery50Icon from "./icons/battery_50.js";
import Battery60Icon from "./icons/battery_60.js";
import Battery80Icon from "./icons/battery_80.js";
import Battery90Icon from "./icons/battery_90.js";
import BatteryAlertIcon from "./icons/battery_alert.js";
import BatteryCharging20Icon from "./icons/battery_charging_20.js";
import BatteryCharging30Icon from "./icons/battery_charging_30.js";
import BatteryCharging50Icon from "./icons/battery_charging_50.js";
import BatteryCharging60Icon from "./icons/battery_charging_60.js";
import BatteryCharging80Icon from "./icons/battery_charging_80.js";
import BatteryCharging90Icon from "./icons/battery_charging_90.js";
import BatteryChargingFullIcon from "./icons/battery_charging_full.js";
import BatteryFullIcon from "./icons/battery_full.js";
import BatteryStdIcon from "./icons/battery_std.js";
import BatteryUnknownIcon from "./icons/battery_unknown.js";
import BeachAccessIcon from "./icons/beach_access.js";
import BeenhereIcon from "./icons/beenhere.js";
import BlockIcon from "./icons/block.js";
import BluetoothIcon from "./icons/bluetooth.js";
import BluetoothAudioIcon from "./icons/bluetooth_audio.js";
import BluetoothConnectedIcon from "./icons/bluetooth_connected.js";
import BluetoothDisabledIcon from "./icons/bluetooth_disabled.js";
import BluetoothSearchingIcon from "./icons/bluetooth_searching.js";
import BlurCircularIcon from "./icons/blur_circular.js";
import BlurLinearIcon from "./icons/blur_linear.js";
import BlurOffIcon from "./icons/blur_off.js";
import BlurOnIcon from "./icons/blur_on.js";
import BookIcon from "./icons/book.js";
import BookmarkIcon from "./icons/bookmark.js";
import BookmarkBorderIcon from "./icons/bookmark_border.js";
import BorderAllIcon from "./icons/border_all.js";
import BorderBottomIcon from "./icons/border_bottom.js";
import BorderClearIcon from "./icons/border_clear.js";
import BorderColorIcon from "./icons/border_color.js";
import BorderHorizontalIcon from "./icons/border_horizontal.js";
import BorderInnerIcon from "./icons/border_inner.js";
import BorderLeftIcon from "./icons/border_left.js";
import BorderOuterIcon from "./icons/border_outer.js";
import BorderRightIcon from "./icons/border_right.js";
import BorderStyleIcon from "./icons/border_style.js";
import BorderTopIcon from "./icons/border_top.js";
import BorderVerticalIcon from "./icons/border_vertical.js";
import BrandingWatermarkIcon from "./icons/branding_watermark.js";
import Brightness1Icon from "./icons/brightness_1.js";
import Brightness2Icon from "./icons/brightness_2.js";
import Brightness3Icon from "./icons/brightness_3.js";
import Brightness4Icon from "./icons/brightness_4.js";
import Brightness5Icon from "./icons/brightness_5.js";
import Brightness6Icon from "./icons/brightness_6.js";
import Brightness7Icon from "./icons/brightness_7.js";
import BrightnessAutoIcon from "./icons/brightness_auto.js";
import BrightnessHighIcon from "./icons/brightness_high.js";
import BrightnessLowIcon from "./icons/brightness_low.js";
import BrightnessMediumIcon from "./icons/brightness_medium.js";
import BrokenImageIcon from "./icons/broken_image.js";
import BrushIcon from "./icons/brush.js";
import BubbleChartIcon from "./icons/bubble_chart.js";
import BugReportIcon from "./icons/bug_report.js";
import BuildIcon from "./icons/build.js";
import BurstModeIcon from "./icons/burst_mode.js";
import BusinessIcon from "./icons/business.js";
import BusinessCenterIcon from "./icons/business_center.js";
import CachedIcon from "./icons/cached.js";
import CakeIcon from "./icons/cake.js";
import CallIcon from "./icons/call.js";
import CallEndIcon from "./icons/call_end.js";
import CallMadeIcon from "./icons/call_made.js";
import CallMergeIcon from "./icons/call_merge.js";
import CallMissedIcon from "./icons/call_missed.js";
import CallMissedOutgoingIcon from "./icons/call_missed_outgoing.js";
import CallReceivedIcon from "./icons/call_received.js";
import CallSplitIcon from "./icons/call_split.js";
import CallToActionIcon from "./icons/call_to_action.js";
import CameraIcon from "./icons/camera.js";
import CameraAltIcon from "./icons/camera_alt.js";
import CameraFrontIcon from "./icons/camera_front.js";
import CameraRearIcon from "./icons/camera_rear.js";
import CameraRollIcon from "./icons/camera_roll.js";
import CancelIcon from "./icons/cancel.js";
import CardGiftcardIcon from "./icons/card_giftcard.js";
import CardMembershipIcon from "./icons/card_membership.js";
import CardTravelIcon from "./icons/card_travel.js";
import CasinoIcon from "./icons/casino.js";
import CastIcon from "./icons/cast.js";
import CastConnectedIcon from "./icons/cast_connected.js";
import CenterFocusStrongIcon from "./icons/center_focus_strong.js";
import CenterFocusWeakIcon from "./icons/center_focus_weak.js";
import ChangeHistoryIcon from "./icons/change_history.js";
import ChatIcon from "./icons/chat.js";
import ChatBubbleIcon from "./icons/chat_bubble.js";
import ChatBubbleOutlineIcon from "./icons/chat_bubble_outline.js";
import CheckIcon from "./icons/check.js";
import CheckBoxIcon from "./icons/check_box.js";
import CheckBoxOutlineBlankIcon from "./icons/check_box_outline_blank.js";
import CheckCircleIcon from "./icons/check_circle.js";
import ChevronLeftIcon from "./icons/chevron_left.js";
import ChevronRightIcon from "./icons/chevron_right.js";
import ChildCareIcon from "./icons/child_care.js";
import ChildFriendlyIcon from "./icons/child_friendly.js";
import ChromeReaderModeIcon from "./icons/chrome_reader_mode.js";
import ClassIcon from "./icons/class.js";
import ClearIcon from "./icons/clear.js";
import ClearAllIcon from "./icons/clear_all.js";
import CloseIcon from "./icons/close.js";
import ClosedCaptionIcon from "./icons/closed_caption.js";
import CloudIcon from "./icons/cloud.js";
import CloudCircleIcon from "./icons/cloud_circle.js";
import CloudDoneIcon from "./icons/cloud_done.js";
import CloudDownloadIcon from "./icons/cloud_download.js";
import CloudOffIcon from "./icons/cloud_off.js";
import CloudQueueIcon from "./icons/cloud_queue.js";
import CloudUploadIcon from "./icons/cloud_upload.js";
import CodeIcon from "./icons/code.js";
import CollectionsIcon from "./icons/collections.js";
import ColorLensIcon from "./icons/color_lens.js";
import ColorizeIcon from "./icons/colorize.js";
import CommentIcon from "./icons/comment.js";
import CompareIcon from "./icons/compare.js";
import CompareArrowsIcon from "./icons/compare_arrows.js";
import ComputerIcon from "./icons/computer.js";
import ConfirmationNumberIcon from "./icons/confirmation_number.js";
import ContactMailIcon from "./icons/contact_mail.js";
import ContactPhoneIcon from "./icons/contact_phone.js";
import ContactsIcon from "./icons/contacts.js";
import ContentCopyIcon from "./icons/content_copy.js";
import ContentCutIcon from "./icons/content_cut.js";
import ContentPasteIcon from "./icons/content_paste.js";
import ControlPointIcon from "./icons/control_point.js";
import ControlPointDuplicateIcon from "./icons/control_point_duplicate.js";
import CopyrightIcon from "./icons/copyright.js";
import CreateIcon from "./icons/create.js";
import CreateNewFolderIcon from "./icons/create_new_folder.js";
import CreditCardIcon from "./icons/credit_card.js";
import CropIcon from "./icons/crop.js";
import Crop169Icon from "./icons/crop_16_9.js";
import Crop32Icon from "./icons/crop_3_2.js";
import Crop54Icon from "./icons/crop_5_4.js";
import Crop75Icon from "./icons/crop_7_5.js";
import CropDinIcon from "./icons/crop_din.js";
import CropFreeIcon from "./icons/crop_free.js";
import CropLandscapeIcon from "./icons/crop_landscape.js";
import CropOriginalIcon from "./icons/crop_original.js";
import CropPortraitIcon from "./icons/crop_portrait.js";
import CropRotateIcon from "./icons/crop_rotate.js";
import CropSquareIcon from "./icons/crop_square.js";
import DashboardIcon from "./icons/dashboard.js";
import DataUsageIcon from "./icons/data_usage.js";
import DateRangeIcon from "./icons/date_range.js";
import DehazeIcon from "./icons/dehaze.js";
import DeleteIcon from "./icons/delete.js";
import DeleteForeverIcon from "./icons/delete_forever.js";
import DeleteSweepIcon from "./icons/delete_sweep.js";
import DescriptionIcon from "./icons/description.js";
import DesktopMacIcon from "./icons/desktop_mac.js";
import DesktopWindowsIcon from "./icons/desktop_windows.js";
import DetailsIcon from "./icons/details.js";
import DeveloperBoardIcon from "./icons/developer_board.js";
import DeveloperModeIcon from "./icons/developer_mode.js";
import DevicesIcon from "./icons/devices.js";
import DevicesOtherIcon from "./icons/devices_other.js";
import DialerSipIcon from "./icons/dialer_sip.js";
import DialpadIcon from "./icons/dialpad.js";
import DirectionsIcon from "./icons/directions.js";
import DirectionsBikeIcon from "./icons/directions_bike.js";
import DirectionsBoatIcon from "./icons/directions_boat.js";
import DirectionsBusIcon from "./icons/directions_bus.js";
import DirectionsCarIcon from "./icons/directions_car.js";
import DirectionsRailwayIcon from "./icons/directions_railway.js";
import DirectionsRunIcon from "./icons/directions_run.js";
import DirectionsSubwayIcon from "./icons/directions_subway.js";
import DirectionsTransitIcon from "./icons/directions_transit.js";
import DirectionsWalkIcon from "./icons/directions_walk.js";
import DiscFullIcon from "./icons/disc_full.js";
import DnsIcon from "./icons/dns.js";
import DoNotDisturbIcon from "./icons/do_not_disturb.js";
import DoNotDisturbAltIcon from "./icons/do_not_disturb_alt.js";
import DoNotDisturbOffIcon from "./icons/do_not_disturb_off.js";
import DoNotDisturbOnIcon from "./icons/do_not_disturb_on.js";
import DockIcon from "./icons/dock.js";
import DomainIcon from "./icons/domain.js";
import DoneIcon from "./icons/done.js";
import DoneAllIcon from "./icons/done_all.js";
import DonutLargeIcon from "./icons/donut_large.js";
import DonutSmallIcon from "./icons/donut_small.js";
import DraftsIcon from "./icons/drafts.js";
import DragHandleIcon from "./icons/drag_handle.js";
import DriveEtaIcon from "./icons/drive_eta.js";
import DvrIcon from "./icons/dvr.js";
import EditIcon from "./icons/edit.js";
import EditLocationIcon from "./icons/edit_location.js";
import EmailIcon from "./icons/email.js";
import EnhancedEncryptionIcon from "./icons/enhanced_encryption.js";
import EqualizerIcon from "./icons/equalizer.js";
import ErrorIcon from "./icons/error.js";
import ErrorOutlineIcon from "./icons/error_outline.js";
import EuroSymbolIcon from "./icons/euro_symbol.js";
import EvStationIcon from "./icons/ev_station.js";
import EventIcon from "./icons/event.js";
import EventAvailableIcon from "./icons/event_available.js";
import EventBusyIcon from "./icons/event_busy.js";
import EventNoteIcon from "./icons/event_note.js";
import EventSeatIcon from "./icons/event_seat.js";
import ExitToAppIcon from "./icons/exit_to_app.js";
import ExpandLessIcon from "./icons/expand_less.js";
import ExpandMoreIcon from "./icons/expand_more.js";
import ExplicitIcon from "./icons/explicit.js";
import ExploreIcon from "./icons/explore.js";
import ExposureIcon from "./icons/exposure.js";
import ExposureNeg1Icon from "./icons/exposure_neg_1.js";
import ExposureNeg2Icon from "./icons/exposure_neg_2.js";
import ExposurePlus1Icon from "./icons/exposure_plus_1.js";
import ExposurePlus2Icon from "./icons/exposure_plus_2.js";
import ExposureZeroIcon from "./icons/exposure_zero.js";
import ExtensionIcon from "./icons/extension.js";
import FaceIcon from "./icons/face.js";
import FastForwardIcon from "./icons/fast_forward.js";
import FastRewindIcon from "./icons/fast_rewind.js";
import FavoriteIcon from "./icons/favorite.js";
import FavoriteBorderIcon from "./icons/favorite_border.js";
import FeaturedPlayListIcon from "./icons/featured_play_list.js";
import FeaturedVideoIcon from "./icons/featured_video.js";
import FeedbackIcon from "./icons/feedback.js";
import FiberDvrIcon from "./icons/fiber_dvr.js";
import FiberManualRecordIcon from "./icons/fiber_manual_record.js";
import FiberNewIcon from "./icons/fiber_new.js";
import FiberPinIcon from "./icons/fiber_pin.js";
import FiberSmartRecordIcon from "./icons/fiber_smart_record.js";
import FileDownloadIcon from "./icons/file_download.js";
import FileUploadIcon from "./icons/file_upload.js";
import FilterIcon from "./icons/filter.js";
import Filter1Icon from "./icons/filter_1.js";
import Filter2Icon from "./icons/filter_2.js";
import Filter3Icon from "./icons/filter_3.js";
import Filter4Icon from "./icons/filter_4.js";
import Filter5Icon from "./icons/filter_5.js";
import Filter6Icon from "./icons/filter_6.js";
import Filter7Icon from "./icons/filter_7.js";
import Filter8Icon from "./icons/filter_8.js";
import Filter9Icon from "./icons/filter_9.js";
import Filter9PlusIcon from "./icons/filter_9_plus.js";
import FilterBAndWIcon from "./icons/filter_b_and_w.js";
import FilterCenterFocusIcon from "./icons/filter_center_focus.js";
import FilterDramaIcon from "./icons/filter_drama.js";
import FilterFramesIcon from "./icons/filter_frames.js";
import FilterHdrIcon from "./icons/filter_hdr.js";
import FilterListIcon from "./icons/filter_list.js";
import FilterNoneIcon from "./icons/filter_none.js";
import FilterTiltShiftIcon from "./icons/filter_tilt_shift.js";
import FilterVintageIcon from "./icons/filter_vintage.js";
import FindInPageIcon from "./icons/find_in_page.js";
import FindReplaceIcon from "./icons/find_replace.js";
import FingerprintIcon from "./icons/fingerprint.js";
import FirstPageIcon from "./icons/first_page.js";
import FitnessCenterIcon from "./icons/fitness_center.js";
import FlagIcon from "./icons/flag.js";
import FlareIcon from "./icons/flare.js";
import FlashAutoIcon from "./icons/flash_auto.js";
import FlashOffIcon from "./icons/flash_off.js";
import FlashOnIcon from "./icons/flash_on.js";
import FlightIcon from "./icons/flight.js";
import FlightLandIcon from "./icons/flight_land.js";
import FlightTakeoffIcon from "./icons/flight_takeoff.js";
import FlipIcon from "./icons/flip.js";
import FlipToBackIcon from "./icons/flip_to_back.js";
import FlipToFrontIcon from "./icons/flip_to_front.js";
import FolderIcon from "./icons/folder.js";
import FolderOpenIcon from "./icons/folder_open.js";
import FolderSharedIcon from "./icons/folder_shared.js";
import FolderSpecialIcon from "./icons/folder_special.js";
import FormatAlignCenterIcon from "./icons/format_align_center.js";
import FormatAlignJustifyIcon from "./icons/format_align_justify.js";
import FormatAlignLeftIcon from "./icons/format_align_left.js";
import FormatAlignRightIcon from "./icons/format_align_right.js";
import FormatBoldIcon from "./icons/format_bold.js";
import FormatClearIcon from "./icons/format_clear.js";
import FormatColorFillIcon from "./icons/format_color_fill.js";
import FormatColorResetIcon from "./icons/format_color_reset.js";
import FormatColorTextIcon from "./icons/format_color_text.js";
import FormatIndentDecreaseIcon from "./icons/format_indent_decrease.js";
import FormatIndentIncreaseIcon from "./icons/format_indent_increase.js";
import FormatItal48PxIcon from "./icons/format_ital48px.js";
import FormatLineSpacingIcon from "./icons/format_line_spacing.js";
import FormatListBulletedIcon from "./icons/format_list_bulleted.js";
import FormatListNumberedIcon from "./icons/format_list_numbered.js";
import FormatPaintIcon from "./icons/format_paint.js";
import FormatQuoteIcon from "./icons/format_quote.js";
import FormatShapesIcon from "./icons/format_shapes.js";
import FormatSizeIcon from "./icons/format_size.js";
import FormatStrikethroughIcon from "./icons/format_strikethrough.js";
import FormatTextdirectionLToRIcon from "./icons/format_textdirection_l_to_r.js";
import FormatTextdirectionRToLIcon from "./icons/format_textdirection_r_to_l.js";
import FormatUnderlinedIcon from "./icons/format_underlined.js";
import ForumIcon from "./icons/forum.js";
import ForwardIcon from "./icons/forward.js";
import Forward10Icon from "./icons/forward_10.js";
import Forward30Icon from "./icons/forward_30.js";
import Forward5Icon from "./icons/forward_5.js";
import FreeBreakfastIcon from "./icons/free_breakfast.js";
import FullscreenIcon from "./icons/fullscreen.js";
import FullscreenExitIcon from "./icons/fullscreen_exit.js";
import FunctionsIcon from "./icons/functions.js";
import GTranslateIcon from "./icons/g_translate.js";
import GamepadIcon from "./icons/gamepad.js";
import GamesIcon from "./icons/games.js";
import GavelIcon from "./icons/gavel.js";
import GestureIcon from "./icons/gesture.js";
import GetAppIcon from "./icons/get_app.js";
import GolfCourseIcon from "./icons/golf_course.js";
import GpsFixedIcon from "./icons/gps_fixed.js";
import GpsNotFixedIcon from "./icons/gps_not_fixed.js";
import GpsOffIcon from "./icons/gps_off.js";
import GradeIcon from "./icons/grade.js";
import GradientIcon from "./icons/gradient.js";
import GrainIcon from "./icons/grain.js";
import GrapheqIcon from "./icons/grapheq.js";
import GridOffIcon from "./icons/grid_off.js";
import GridOnIcon from "./icons/grid_on.js";
import GroupIcon from "./icons/group.js";
import GroupAddIcon from "./icons/group_add.js";
import GroupWorkIcon from "./icons/group_work.js";
import HdrOffIcon from "./icons/hdr_off.js";
import HdrOnIcon from "./icons/hdr_on.js";
import HdrStrongIcon from "./icons/hdr_strong.js";
import HdrWeakIcon from "./icons/hdr_weak.js";
import HeadsetIcon from "./icons/headset.js";
import HeadsetM48PxIcon from "./icons/headset_m48px.js";
import HealingIcon from "./icons/healing.js";
import HearingIcon from "./icons/hearing.js";
import HelpIcon from "./icons/help.js";
import HighQualityIcon from "./icons/high_quality.js";
import HighlightIcon from "./icons/highlight.js";
import HighlightOffIcon from "./icons/highlight_off.js";
import HistoryIcon from "./icons/history.js";
import HomeIcon from "./icons/home.js";
import HotTubIcon from "./icons/hot_tub.js";
import HotelIcon from "./icons/hotel.js";
import HourglassEmptyIcon from "./icons/hourglass_empty.js";
import HourglassFullIcon from "./icons/hourglass_full.js";
import HttpIcon from "./icons/http.js";
import HttpsIcon from "./icons/https.js";
import ImageIcon from "./icons/image.js";
import ImageAspectRatioIcon from "./icons/image_aspect_ratio.js";
import ImportContactsIcon from "./icons/import_contacts.js";
import ImportExportIcon from "./icons/import_export.js";
import ImportantDevicesIcon from "./icons/important_devices.js";
import InboxIcon from "./icons/inbox.js";
import InfoIcon from "./icons/info.js";
import InfoOutlineIcon from "./icons/info_outline.js";
import InputIcon from "./icons/input.js";
import InsertChartIcon from "./icons/insert_chart.js";
import InsertCommentIcon from "./icons/insert_comment.js";
import InsertDriveFileIcon from "./icons/insert_drive_file.js";
import InsertEmoticonIcon from "./icons/insert_emoticon.js";
import InsertInvitationIcon from "./icons/insert_invitation.js";
import InsertLinkIcon from "./icons/insert_link.js";
import InsertPhotoIcon from "./icons/insert_photo.js";
import InvertColorsIcon from "./icons/invert_colors.js";
import InvertColorsOffIcon from "./icons/invert_colors_off.js";
import IsoIcon from "./icons/iso.js";
import KeyboardIcon from "./icons/keyboard.js";
import KeyboardArrowDownIcon from "./icons/keyboard_arrow_down.js";
import KeyboardArrowLeftIcon from "./icons/keyboard_arrow_left.js";
import KeyboardArrowRightIcon from "./icons/keyboard_arrow_right.js";
import KeyboardArrowUpIcon from "./icons/keyboard_arrow_up.js";
import KeyboardBackspaceIcon from "./icons/keyboard_backspace.js";
import KeyboardCapslockIcon from "./icons/keyboard_capslock.js";
import KeyboardHideIcon from "./icons/keyboard_hide.js";
import KeyboardReturnIcon from "./icons/keyboard_return.js";
import KeyboardTabIcon from "./icons/keyboard_tab.js";
import KeyboardVoiceIcon from "./icons/keyboard_voice.js";
import KitchenIcon from "./icons/kitchen.js";
import LabelIcon from "./icons/label.js";
import LabelOutlineIcon from "./icons/label_outline.js";
import LandscapeIcon from "./icons/landscape.js";
import LanguageIcon from "./icons/language.js";
import LaptopIcon from "./icons/laptop.js";
import LaptopChromebookIcon from "./icons/laptop_chromebook.js";
import LaptopMacIcon from "./icons/laptop_mac.js";
import LaptopWindowsIcon from "./icons/laptop_windows.js";
import LastPageIcon from "./icons/last_page.js";
import LaunchIcon from "./icons/launch.js";
import LayersIcon from "./icons/layers.js";
import LayersClearIcon from "./icons/layers_clear.js";
import LeakAddIcon from "./icons/leak_add.js";
import LeakRemoveIcon from "./icons/leak_remove.js";
import LensIcon from "./icons/lens.js";
import LibraryAddIcon from "./icons/library_add.js";
import LibraryBooksIcon from "./icons/library_books.js";
import LibraryMus48PxIcon from "./icons/library_mus48px.js";
import LightbulbOutlineIcon from "./icons/lightbulb_outline.js";
import LineStyleIcon from "./icons/line_style.js";
import LineWeightIcon from "./icons/line_weight.js";
import LinearScaleIcon from "./icons/linear_scale.js";
import LinkIcon from "./icons/link.js";
import LinkedCameraIcon from "./icons/linked_camera.js";
import ListIcon from "./icons/list.js";
import LiveHelpIcon from "./icons/live_help.js";
import LiveTvIcon from "./icons/live_tv.js";
import LocalActivityIcon from "./icons/local_activity.js";
import LocalAirportIcon from "./icons/local_airport.js";
import LocalAtmIcon from "./icons/local_atm.js";
import LocalBarIcon from "./icons/local_bar.js";
import LocalCafeIcon from "./icons/local_cafe.js";
import LocalCarWashIcon from "./icons/local_car_wash.js";
import LocalConvenienceStoreIcon from "./icons/local_convenience_store.js";
import LocalDiningIcon from "./icons/local_dining.js";
import LocalDrinkIcon from "./icons/local_drink.js";
import LocalFloristIcon from "./icons/local_florist.js";
import LocalGasStationIcon from "./icons/local_gas_station.js";
import LocalGroceryStoreIcon from "./icons/local_grocery_store.js";
import LocalHospitalIcon from "./icons/local_hospital.js";
import LocalHotelIcon from "./icons/local_hotel.js";
import LocalLaundryServiceIcon from "./icons/local_laundry_service.js";
import LocalLibraryIcon from "./icons/local_library.js";
import LocalMallIcon from "./icons/local_mall.js";
import LocalMoviesIcon from "./icons/local_movies.js";
import LocalOfferIcon from "./icons/local_offer.js";
import LocalParkingIcon from "./icons/local_parking.js";
import LocalPharmacyIcon from "./icons/local_pharmacy.js";
import LocalPhoneIcon from "./icons/local_phone.js";
import LocalPizzaIcon from "./icons/local_pizza.js";
import LocalPlayIcon from "./icons/local_play.js";
import LocalPostOfficeIcon from "./icons/local_post_office.js";
import LocalPrintshopIcon from "./icons/local_printshop.js";
import LocalSeeIcon from "./icons/local_see.js";
import LocalShippingIcon from "./icons/local_shipping.js";
import LocalTaxiIcon from "./icons/local_taxi.js";
import LocationCityIcon from "./icons/location_city.js";
import LocationDisabledIcon from "./icons/location_disabled.js";
import LocationOffIcon from "./icons/location_off.js";
import LocationOnIcon from "./icons/location_on.js";
import LocationSearchingIcon from "./icons/location_searching.js";
import LockIcon from "./icons/lock.js";
import LockOpenIcon from "./icons/lock_open.js";
import LockOutlineIcon from "./icons/lock_outline.js";
import LooksIcon from "./icons/looks.js";
import Looks3Icon from "./icons/looks_3.js";
import Looks4Icon from "./icons/looks_4.js";
import Looks5Icon from "./icons/looks_5.js";
import Looks6Icon from "./icons/looks_6.js";
import LooksOneIcon from "./icons/looks_one.js";
import LooksTwoIcon from "./icons/looks_two.js";
import LoopIcon from "./icons/loop.js";
import LoupeIcon from "./icons/loupe.js";
import LowPriorityIcon from "./icons/low_priority.js";
import LoyaltyIcon from "./icons/loyalty.js";
import M48PxIcon from "./icons/m48px.js";
import MailIcon from "./icons/mail.js";
import MailOutlineIcon from "./icons/mail_outline.js";
import MapIcon from "./icons/map.js";
import MarkunreadIcon from "./icons/markunread.js";
import MarkunreadMailboxIcon from "./icons/markunread_mailbox.js";
import MemoryIcon from "./icons/memory.js";
import MenuIcon from "./icons/menu.js";
import MergeTypeIcon from "./icons/merge_type.js";
import MessageIcon from "./icons/message.js";
import MmsIcon from "./icons/mms.js";
import MnoneIcon from "./icons/mnone.js";
import ModeCommentIcon from "./icons/mode_comment.js";
import ModeEditIcon from "./icons/mode_edit.js";
import MoffIcon from "./icons/moff.js";
import MonetizationOnIcon from "./icons/monetization_on.js";
import MonochromePhotosIcon from "./icons/monochrome_photos.js";
import MoodIcon from "./icons/mood.js";
import MoodBadIcon from "./icons/mood_bad.js";
import MoreIcon from "./icons/more.js";
import MoreHorizIcon from "./icons/more_horiz.js";
import MoreVertIcon from "./icons/more_vert.js";
import MotorcycleIcon from "./icons/motorcycle.js";
import MouseIcon from "./icons/mouse.js";
import MoveToInboxIcon from "./icons/move_to_inbox.js";
import MovieIcon from "./icons/movie.js";
import MovieCreationIcon from "./icons/movie_creation.js";
import MovieFilterIcon from "./icons/movie_filter.js";
import MultilineChartIcon from "./icons/multiline_chart.js";
import MusnoteIcon from "./icons/musnote.js";
import MusvideoIcon from "./icons/musvideo.js";
import MyLocationIcon from "./icons/my_location.js";
import NatureIcon from "./icons/nature.js";
import NaturePeopleIcon from "./icons/nature_people.js";
import NavigateBeforeIcon from "./icons/navigate_before.js";
import NavigateNextIcon from "./icons/navigate_next.js";
import NavigationIcon from "./icons/navigation.js";
import NearMeIcon from "./icons/near_me.js";
import NetworkCellIcon from "./icons/network_cell.js";
import NetworkCheckIcon from "./icons/network_check.js";
import NetworkLockedIcon from "./icons/network_locked.js";
import NetworkWifiIcon from "./icons/network_wifi.js";
import NewReleasesIcon from "./icons/new_releases.js";
import NextWeekIcon from "./icons/next_week.js";
import NfcIcon from "./icons/nfc.js";
import NoEncryptionIcon from "./icons/no_encryption.js";
import NoSimIcon from "./icons/no_sim.js";
import NotInterestedIcon from "./icons/not_interested.js";
import NoteIcon from "./icons/note.js";
import NoteAddIcon from "./icons/note_add.js";
import NotificationsIcon from "./icons/notifications.js";
import NotificationsActiveIcon from "./icons/notifications_active.js";
import NotificationsNoneIcon from "./icons/notifications_none.js";
import NotificationsOffIcon from "./icons/notifications_off.js";
import NotificationsPausedIcon from "./icons/notifications_paused.js";
import OndemandVideoIcon from "./icons/ondemand_video.js";
import OpacityIcon from "./icons/opacity.js";
import OpenInBrowserIcon from "./icons/open_in_browser.js";
import OpenInNewIcon from "./icons/open_in_new.js";
import OpenWithIcon from "./icons/open_with.js";
import PagesIcon from "./icons/pages.js";
import PageviewIcon from "./icons/pageview.js";
import PaletteIcon from "./icons/palette.js";
import PanToolIcon from "./icons/pan_tool.js";
import PanoramaIcon from "./icons/panorama.js";
import PanoramaFishEyeIcon from "./icons/panorama_fish_eye.js";
import PanoramaHorizontalIcon from "./icons/panorama_horizontal.js";
import PanoramaVerticalIcon from "./icons/panorama_vertical.js";
import PanoramaWideAngleIcon from "./icons/panorama_wide_angle.js";
import PartyModeIcon from "./icons/party_mode.js";
import PauseIcon from "./icons/pause.js";
import PauseCircleFilledIcon from "./icons/pause_circle_filled.js";
import PauseCircleOutlineIcon from "./icons/pause_circle_outline.js";
import PaymentIcon from "./icons/payment.js";
import PeopleIcon from "./icons/people.js";
import PeopleOutlineIcon from "./icons/people_outline.js";
import PermCameraM48PxIcon from "./icons/perm_camera_m48px.js";
import PermContactCalendarIcon from "./icons/perm_contact_calendar.js";
import PermDataSettingIcon from "./icons/perm_data_setting.js";
import PermDeviceInformationIcon from "./icons/perm_device_information.js";
import PermIdentityIcon from "./icons/perm_identity.js";
import PermMediaIcon from "./icons/perm_media.js";
import PermPhoneMsgIcon from "./icons/perm_phone_msg.js";
import PermScanWifiIcon from "./icons/perm_scan_wifi.js";
import PersonIcon from "./icons/person.js";
import PersonAddIcon from "./icons/person_add.js";
import PersonOutlineIcon from "./icons/person_outline.js";
import PersonPinIcon from "./icons/person_pin.js";
import PersonPinCircleIcon from "./icons/person_pin_circle.js";
import PersonalVideoIcon from "./icons/personal_video.js";
import PetsIcon from "./icons/pets.js";
import PhoneIcon from "./icons/phone.js";
import PhoneAndroidIcon from "./icons/phone_android.js";
import PhoneBluetoothSpeakerIcon from "./icons/phone_bluetooth_speaker.js";
import PhoneForwardedIcon from "./icons/phone_forwarded.js";
import PhoneInTalkIcon from "./icons/phone_in_talk.js";
import PhoneIphoneIcon from "./icons/phone_iphone.js";
import PhoneLockedIcon from "./icons/phone_locked.js";
import PhoneMissedIcon from "./icons/phone_missed.js";
import PhonePausedIcon from "./icons/phone_paused.js";
import PhonelinkIcon from "./icons/phonelink.js";
import PhonelinkOffIcon from "./icons/phonelink_off.js";
import PhotoIcon from "./icons/photo.js";
import PhotoAlbumIcon from "./icons/photo_album.js";
import PhotoCameraIcon from "./icons/photo_camera.js";
import PhotoFilterIcon from "./icons/photo_filter.js";
import PhotoLibraryIcon from "./icons/photo_library.js";
import PictureAsPdfIcon from "./icons/picture_as_pdf.js";
import PictureInPictureIcon from "./icons/picture_in_picture.js";
import PictureInPictureAltIcon from "./icons/picture_in_picture_alt.js";
import PieChartIcon from "./icons/pie_chart.js";
import PieChartOutlinedIcon from "./icons/pie_chart_outlined.js";
import PinDropIcon from "./icons/pin_drop.js";
import PlaceIcon from "./icons/place.js";
import PlayArrowIcon from "./icons/play_arrow.js";
import PlayCircleFilledIcon from "./icons/play_circle_filled.js";
import PlayCircleFilledWhiteIcon from "./icons/play_circle_filled_white.js";
import PlayCircleOutlineIcon from "./icons/play_circle_outline.js";
import PlayForWorkIcon from "./icons/play_for_work.js";
import PlaylistAddIcon from "./icons/playlist_add.js";
import PlaylistAddCheckIcon from "./icons/playlist_add_check.js";
import PlaylistPlayIcon from "./icons/playlist_play.js";
import PlusOneIcon from "./icons/plus_one.js";
import PollIcon from "./icons/poll.js";
import PolymerIcon from "./icons/polymer.js";
import PoolIcon from "./icons/pool.js";
import PortableWifiOffIcon from "./icons/portable_wifi_off.js";
import PortraitIcon from "./icons/portrait.js";
import PowerIcon from "./icons/power.js";
import PowerInputIcon from "./icons/power_input.js";
import PowerSettingsNewIcon from "./icons/power_settings_new.js";
import PregnantWomanIcon from "./icons/pregnant_woman.js";
import PresentToAllIcon from "./icons/present_to_all.js";
import PrintIcon from "./icons/print.js";
import PriorityHighIcon from "./icons/priority_high.js";
import Publ48PxIcon from "./icons/publ48px.js";
import PublishIcon from "./icons/publish.js";
import QueryBuilderIcon from "./icons/query_builder.js";
import QuestionAnswerIcon from "./icons/question_answer.js";
import QueueIcon from "./icons/queue.js";
import QueueMus48PxIcon from "./icons/queue_mus48px.js";
import QueuePlayNextIcon from "./icons/queue_play_next.js";
import RadioIcon from "./icons/radio.js";
import RadioButtonCheckedIcon from "./icons/radio_button_checked.js";
import RadioButtonUncheckedIcon from "./icons/radio_button_unchecked.js";
import RateReviewIcon from "./icons/rate_review.js";
import ReceiptIcon from "./icons/receipt.js";
import RecentActorsIcon from "./icons/recent_actors.js";
import RecordVoiceOverIcon from "./icons/record_voice_over.js";
import RedeemIcon from "./icons/redeem.js";
import RedoIcon from "./icons/redo.js";
import RefreshIcon from "./icons/refresh.js";
import RemoveIcon from "./icons/remove.js";
import RemoveCircleIcon from "./icons/remove_circle.js";
import RemoveCircleOutlineIcon from "./icons/remove_circle_outline.js";
import RemoveFromQueueIcon from "./icons/remove_from_queue.js";
import RemoveRedEyeIcon from "./icons/remove_red_eye.js";
import RemoveShoppingCartIcon from "./icons/remove_shopping_cart.js";
import RepeatIcon from "./icons/repeat.js";
import RepeatOneIcon from "./icons/repeat_one.js";
import ReplayIcon from "./icons/replay.js";
import Replay10Icon from "./icons/replay_10.js";
import Replay30Icon from "./icons/replay_30.js";
import Replay5Icon from "./icons/replay_5.js";
import ReplyIcon from "./icons/reply.js";
import ReplyAllIcon from "./icons/reply_all.js";
import ReportIcon from "./icons/report.js";
import ReportProblemIcon from "./icons/report_problem.js";
import RestaurantIcon from "./icons/restaurant.js";
import RestaurantMenuIcon from "./icons/restaurant_menu.js";
import RestoreIcon from "./icons/restore.js";
import RestorePageIcon from "./icons/restore_page.js";
import RingVolumeIcon from "./icons/ring_volume.js";
import RoomIcon from "./icons/room.js";
import RoomServiceIcon from "./icons/room_service.js";
import Rotate90DegreesCcwIcon from "./icons/rotate_90_degrees_ccw.js";
import RotateLeftIcon from "./icons/rotate_left.js";
import RotateRightIcon from "./icons/rotate_right.js";
import RoundedCornerIcon from "./icons/rounded_corner.js";
import RouterIcon from "./icons/router.js";
import RowingIcon from "./icons/rowing.js";
import RssFeedIcon from "./icons/rss_feed.js";
import RvHookupIcon from "./icons/rv_hookup.js";
import SatelliteIcon from "./icons/satellite.js";
import SaveIcon from "./icons/save.js";
import ScannerIcon from "./icons/scanner.js";
import ScheduleIcon from "./icons/schedule.js";
import SchoolIcon from "./icons/school.js";
import ScreenLockLandscapeIcon from "./icons/screen_lock_landscape.js";
import ScreenLockPortraitIcon from "./icons/screen_lock_portrait.js";
import ScreenLockRotationIcon from "./icons/screen_lock_rotation.js";
import ScreenRotationIcon from "./icons/screen_rotation.js";
import ScreenShareIcon from "./icons/screen_share.js";
import SdCardIcon from "./icons/sd_card.js";
import SdStorageIcon from "./icons/sd_storage.js";
import SearchIcon from "./icons/search.js";
import SecurityIcon from "./icons/security.js";
import SelectAllIcon from "./icons/select_all.js";
import SendIcon from "./icons/send.js";
import SentimentDissatisfiedIcon from "./icons/sentiment_dissatisfied.js";
import SentimentNeutralIcon from "./icons/sentiment_neutral.js";
import SentimentSatisfiedIcon from "./icons/sentiment_satisfied.js";
import SentimentVeryDissatisfiedIcon from "./icons/sentiment_very_dissatisfied.js";
import SentimentVerySatisfiedIcon from "./icons/sentiment_very_satisfied.js";
import SettingsIcon from "./icons/settings.js";
import SettingsApplicationsIcon from "./icons/settings_applications.js";
import SettingsBackupRestoreIcon from "./icons/settings_backup_restore.js";
import SettingsBluetoothIcon from "./icons/settings_bluetooth.js";
import SettingsBrightnessIcon from "./icons/settings_brightness.js";
import SettingsCellIcon from "./icons/settings_cell.js";
import SettingsEthernetIcon from "./icons/settings_ethernet.js";
import SettingsInputAntennaIcon from "./icons/settings_input_antenna.js";
import SettingsInputComponentIcon from "./icons/settings_input_component.js";
import SettingsInputCompositeIcon from "./icons/settings_input_composite.js";
import SettingsInputHdmiIcon from "./icons/settings_input_hdmi.js";
import SettingsInputSvideoIcon from "./icons/settings_input_svideo.js";
import SettingsOverscanIcon from "./icons/settings_overscan.js";
import SettingsPhoneIcon from "./icons/settings_phone.js";
import SettingsPowerIcon from "./icons/settings_power.js";
import SettingsRemoteIcon from "./icons/settings_remote.js";
import SettingsSystemDaydreamIcon from "./icons/settings_system_daydream.js";
import SettingsVoiceIcon from "./icons/settings_voice.js";
import ShareIcon from "./icons/share.js";
import ShopIcon from "./icons/shop.js";
import ShopTwoIcon from "./icons/shop_two.js";
import ShoppingBasketIcon from "./icons/shopping_basket.js";
import ShoppingCartIcon from "./icons/shopping_cart.js";
import ShortTextIcon from "./icons/short_text.js";
import ShowChartIcon from "./icons/show_chart.js";
import ShuffleIcon from "./icons/shuffle.js";
import SignalCellular0BarIcon from "./icons/signal_cellular_0_bar.js";
import SignalCellular1BarIcon from "./icons/signal_cellular_1_bar.js";
import SignalCellular2BarIcon from "./icons/signal_cellular_2_bar.js";
import SignalCellular3BarIcon from "./icons/signal_cellular_3_bar.js";
import SignalCellular4BarIcon from "./icons/signal_cellular_4_bar.js";
import SignalCellularConnectedNoInternet0BarIcon from "./icons/signal_cellular_connected_no_internet_0_bar.js";
import SignalCellularConnectedNoInternet1BarIcon from "./icons/signal_cellular_connected_no_internet_1_bar.js";
import SignalCellularConnectedNoInternet2BarIcon from "./icons/signal_cellular_connected_no_internet_2_bar.js";
import SignalCellularConnectedNoInternet3BarIcon from "./icons/signal_cellular_connected_no_internet_3_bar.js";
import SignalCellularConnectedNoInternet4BarIcon from "./icons/signal_cellular_connected_no_internet_4_bar.js";
import SignalCellularNoSimIcon from "./icons/signal_cellular_no_sim.js";
import SignalCellularNullIcon from "./icons/signal_cellular_null.js";
import SignalCellularOffIcon from "./icons/signal_cellular_off.js";
import SignalWifi0BarIcon from "./icons/signal_wifi_0_bar.js";
import SignalWifi1BarIcon from "./icons/signal_wifi_1_bar.js";
import SignalWifi1BarLockIcon from "./icons/signal_wifi_1_bar_lock.js";
import SignalWifi2BarIcon from "./icons/signal_wifi_2_bar.js";
import SignalWifi2BarLockIcon from "./icons/signal_wifi_2_bar_lock.js";
import SignalWifi3BarIcon from "./icons/signal_wifi_3_bar.js";
import SignalWifi3BarLockIcon from "./icons/signal_wifi_3_bar_lock.js";
import SignalWifi4BarIcon from "./icons/signal_wifi_4_bar.js";
import SignalWifi4BarLockIcon from "./icons/signal_wifi_4_bar_lock.js";
import SignalWifiOffIcon from "./icons/signal_wifi_off.js";
import SimCardIcon from "./icons/sim_card.js";
import SimCardAlertIcon from "./icons/sim_card_alert.js";
import SkipNextIcon from "./icons/skip_next.js";
import SkipPreviousIcon from "./icons/skip_previous.js";
import SlideshowIcon from "./icons/slideshow.js";
import SlowMotionVideoIcon from "./icons/slow_motion_video.js";
import SmartphoneIcon from "./icons/smartphone.js";
import SmokeFreeIcon from "./icons/smoke_free.js";
import SmokingRoomsIcon from "./icons/smoking_rooms.js";
import SmsIcon from "./icons/sms.js";
import SmsFailedIcon from "./icons/sms_failed.js";
import SnoozeIcon from "./icons/snooze.js";
import SortIcon from "./icons/sort.js";
import SpaIcon from "./icons/spa.js";
import SpaceBarIcon from "./icons/space_bar.js";
import SpeakerIcon from "./icons/speaker.js";
import SpeakerGroupIcon from "./icons/speaker_group.js";
import SpeakerNotesIcon from "./icons/speaker_notes.js";
import SpeakerNotesOffIcon from "./icons/speaker_notes_off.js";
import SpeakerPhoneIcon from "./icons/speaker_phone.js";
import SpellcheckIcon from "./icons/spellcheck.js";
import StarHalfIcon from "./icons/star_half.js";
import StarsIcon from "./icons/stars.js";
import StayCurrentLandscapeIcon from "./icons/stay_current_landscape.js";
import StayCurrentPortraitIcon from "./icons/stay_current_portrait.js";
import StayPrimaryLandscapeIcon from "./icons/stay_primary_landscape.js";
import StayPrimaryPortraitIcon from "./icons/stay_primary_portrait.js";
import StopIcon from "./icons/stop.js";
import StopScreenShareIcon from "./icons/stop_screen_share.js";
import StorageIcon from "./icons/storage.js";
import StoreIcon from "./icons/store.js";
import StoreMallDirectoryIcon from "./icons/store_mall_directory.js";
import StraightenIcon from "./icons/straighten.js";
import StreetviewIcon from "./icons/streetview.js";
import StrikethroughSIcon from "./icons/strikethrough_s.js";
import StyleIcon from "./icons/style.js";
import SubdirectoryArrowLeftIcon from "./icons/subdirectory_arrow_left.js";
import SubdirectoryArrowRightIcon from "./icons/subdirectory_arrow_right.js";
import SubjectIcon from "./icons/subject.js";
import SubscriptionsIcon from "./icons/subscriptions.js";
import SubtitlesIcon from "./icons/subtitles.js";
import SubwayIcon from "./icons/subway.js";
import SupervisorAccountIcon from "./icons/supervisor_account.js";
import SurroundSoundIcon from "./icons/surround_sound.js";
import SwapCallsIcon from "./icons/swap_calls.js";
import SwapHorizIcon from "./icons/swap_horiz.js";
import SwapVertIcon from "./icons/swap_vert.js";
import SwapVerticalCircleIcon from "./icons/swap_vertical_circle.js";
import SwitchCameraIcon from "./icons/switch_camera.js";
import SwitchVideoIcon from "./icons/switch_video.js";
import SyncIcon from "./icons/sync.js";
import SyncDisabledIcon from "./icons/sync_disabled.js";
import SyncProblemIcon from "./icons/sync_problem.js";
import SystemUpdateIcon from "./icons/system_update.js";
import SystemUpdateAltIcon from "./icons/system_update_alt.js";
import TabIcon from "./icons/tab.js";
import TabUnselectedIcon from "./icons/tab_unselected.js";
import TabletIcon from "./icons/tablet.js";
import TabletAndroidIcon from "./icons/tablet_android.js";
import TabletMacIcon from "./icons/tablet_mac.js";
import TagFacesIcon from "./icons/tag_faces.js";
import TapAndPlayIcon from "./icons/tap_and_play.js";
import TerrainIcon from "./icons/terrain.js";
import TextFieldsIcon from "./icons/text_fields.js";
import TextFormatIcon from "./icons/text_format.js";
import TextsmsIcon from "./icons/textsms.js";
import TextureIcon from "./icons/texture.js";
import TheatersIcon from "./icons/theaters.js";
import ThumbDownIcon from "./icons/thumb_down.js";
import ThumbUpIcon from "./icons/thumb_up.js";
import ThumbsUpDownIcon from "./icons/thumbs_up_down.js";
import TimeToLeaveIcon from "./icons/time_to_leave.js";
import TimelapseIcon from "./icons/timelapse.js";
import TimelineIcon from "./icons/timeline.js";
import TimerIcon from "./icons/timer.js";
import Timer10Icon from "./icons/timer_10.js";
import Timer3Icon from "./icons/timer_3.js";
import TimerOffIcon from "./icons/timer_off.js";
import TitleIcon from "./icons/title.js";
import TocIcon from "./icons/toc.js";
import TodayIcon from "./icons/today.js";
import TollIcon from "./icons/toll.js";
import TonalityIcon from "./icons/tonality.js";
import TouchAppIcon from "./icons/touch_app.js";
import ToysIcon from "./icons/toys.js";
import TrackChangesIcon from "./icons/track_changes.js";
import Traff48PxIcon from "./icons/traff48px.js";
import TrainIcon from "./icons/train.js";
import TramIcon from "./icons/tram.js";
import TransferWithinAStationIcon from "./icons/transfer_within_a_station.js";
import TransformIcon from "./icons/transform.js";
import TranslateIcon from "./icons/translate.js";
import TrendingDownIcon from "./icons/trending_down.js";
import TrendingFlatIcon from "./icons/trending_flat.js";
import TrendingUpIcon from "./icons/trending_up.js";
import TuneIcon from "./icons/tune.js";
import TurnedInIcon from "./icons/turned_in.js";
import TurnedInNotIcon from "./icons/turned_in_not.js";
import TvIcon from "./icons/tv.js";
import UnarchiveIcon from "./icons/unarchive.js";
import UndoIcon from "./icons/undo.js";
import UnfoldLessIcon from "./icons/unfold_less.js";
import UnfoldMoreIcon from "./icons/unfold_more.js";
import UpdateIcon from "./icons/update.js";
import UsbIcon from "./icons/usb.js";
import VerifiedUserIcon from "./icons/verified_user.js";
import VerticalAlignBottomIcon from "./icons/vertical_align_bottom.js";
import VerticalAlignCenterIcon from "./icons/vertical_align_center.js";
import VerticalAlignTopIcon from "./icons/vertical_align_top.js";
import VibrationIcon from "./icons/vibration.js";
import VideoCallIcon from "./icons/video_call.js";
import VideoLabelIcon from "./icons/video_label.js";
import VideoLibraryIcon from "./icons/video_library.js";
import VideocamIcon from "./icons/videocam.js";
import VideocamOffIcon from "./icons/videocam_off.js";
import VideogameAssetIcon from "./icons/videogame_asset.js";
import ViewAgendaIcon from "./icons/view_agenda.js";
import ViewArrayIcon from "./icons/view_array.js";
import ViewCarouselIcon from "./icons/view_carousel.js";
import ViewColumnIcon from "./icons/view_column.js";
import ViewComfyIcon from "./icons/view_comfy.js";
import ViewCompactIcon from "./icons/view_compact.js";
import ViewDayIcon from "./icons/view_day.js";
import ViewHeadlineIcon from "./icons/view_headline.js";
import ViewListIcon from "./icons/view_list.js";
import ViewModuleIcon from "./icons/view_module.js";
import ViewQuiltIcon from "./icons/view_quilt.js";
import ViewStreamIcon from "./icons/view_stream.js";
import ViewWeekIcon from "./icons/view_week.js";
import VisibilityIcon from "./icons/visibility.js";
import VisibilityOffIcon from "./icons/visibility_off.js";
import VoiceChatIcon from "./icons/voice_chat.js";
import VoicemailIcon from "./icons/voicemail.js";
import VolumeDownIcon from "./icons/volume_down.js";
import VolumeMuteIcon from "./icons/volume_mute.js";
import VolumeOffIcon from "./icons/volume_off.js";
import VolumeUpIcon from "./icons/volume_up.js";
import VpnKeyIcon from "./icons/vpn_key.js";
import VpnLockIcon from "./icons/vpn_lock.js";
import WallpaperIcon from "./icons/wallpaper.js";
import WarningIcon from "./icons/warning.js";
import WatchIcon from "./icons/watch.js";
import WatchLaterIcon from "./icons/watch_later.js";
import WbAutoIcon from "./icons/wb_auto.js";
import WbCloudyIcon from "./icons/wb_cloudy.js";
import WbIncandescentIcon from "./icons/wb_incandescent.js";
import WbIridescentIcon from "./icons/wb_iridescent.js";
import WbSunnyIcon from "./icons/wb_sunny.js";
import WcIcon from "./icons/wc.js";
import WebIcon from "./icons/web.js";
import WebAssetIcon from "./icons/web_asset.js";
import WeekendIcon from "./icons/weekend.js";
import WhatshotIcon from "./icons/whatshot.js";
import WidgetsIcon from "./icons/widgets.js";
import WifiIcon from "./icons/wifi.js";
import WifiLockIcon from "./icons/wifi_lock.js";
import WifiTetheringIcon from "./icons/wifi_tethering.js";
import WorkIcon from "./icons/work.js";
import WrapTextIcon from "./icons/wrap_text.js";
import YoutubeSearchedForIcon from "./icons/youtube_searched_for.js";
import ZoomOutMapIcon from "./icons/zoom_out_map.js";

export {
  ThreeDRotationIcon,
  AcUnitIcon,
  AccessAlarmIcon,
  AccessAlarmsIcon,
  AccessTimeIcon,
  AccessibilityIcon,
  AccessibleIcon,
  AccountBalanceIcon,
  AccountBalanceWalletIcon,
  AccountBoxIcon,
  AccountCircleIcon,
  AdbIcon,
  AddIcon,
  AddAPhotoIcon,
  AddAlarmIcon,
  AddAlertIcon,
  AddBoxIcon,
  AddCircleIcon,
  AddCircleOutlineIcon,
  AddLocationIcon,
  AddShoppingCartIcon,
  AddToPhotosIcon,
  AddToQueueIcon,
  AdjustIcon,
  AirlineSeatFlatIcon,
  AirlineSeatFlatAngledIcon,
  AirlineSeatIndividualSuiteIcon,
  AirlineSeatLegroomExtraIcon,
  AirlineSeatLegroomNormalIcon,
  AirlineSeatLegroomReducedIcon,
  AirlineSeatReclineExtraIcon,
  AirlineSeatReclineNormalIcon,
  AirplanemodeActiveIcon,
  AirplanemodeInactiveIcon,
  AirplayIcon,
  AirportShuttleIcon,
  AlarmIcon,
  AlarmAddIcon,
  AlarmOffIcon,
  AlarmOnIcon,
  AlbumIcon,
  AllInclusiveIcon,
  AllOutIcon,
  AndroidIcon,
  AnnouncementIcon,
  AppsIcon,
  ArchiveIcon,
  ArrowBackIcon,
  ArrowDownwardIcon,
  ArrowDropDownIcon,
  ArrowDropDownCircleIcon,
  ArrowDropUpIcon,
  ArrowForwardIcon,
  ArrowUpwardIcon,
  ArtTrackIcon,
  AspectRatioIcon,
  AssessmentIcon,
  AssignmentIcon,
  AssignmentIndIcon,
  AssignmentLateIcon,
  AssignmentReturnIcon,
  AssignmentReturnedIcon,
  AssignmentTurnedInIcon,
  AssistantIcon,
  AssistantPhotoIcon,
  AttachFileIcon,
  AttachMoneyIcon,
  AttachmentIcon,
  AudiotrackIcon,
  AutorenewIcon,
  AvTimerIcon,
  BackspaceIcon,
  BackupIcon,
  Battery20Icon,
  Battery30Icon,
  Battery50Icon,
  Battery60Icon,
  Battery80Icon,
  Battery90Icon,
  BatteryAlertIcon,
  BatteryCharging20Icon,
  BatteryCharging30Icon,
  BatteryCharging50Icon,
  BatteryCharging60Icon,
  BatteryCharging80Icon,
  BatteryCharging90Icon,
  BatteryChargingFullIcon,
  BatteryFullIcon,
  BatteryStdIcon,
  BatteryUnknownIcon,
  BeachAccessIcon,
  BeenhereIcon,
  BlockIcon,
  BluetoothIcon,
  BluetoothAudioIcon,
  BluetoothConnectedIcon,
  BluetoothDisabledIcon,
  BluetoothSearchingIcon,
  BlurCircularIcon,
  BlurLinearIcon,
  BlurOffIcon,
  BlurOnIcon,
  BookIcon,
  BookmarkIcon,
  BookmarkBorderIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderClearIcon,
  BorderColorIcon,
  BorderHorizontalIcon,
  BorderInnerIcon,
  BorderLeftIcon,
  BorderOuterIcon,
  BorderRightIcon,
  BorderStyleIcon,
  BorderTopIcon,
  BorderVerticalIcon,
  BrandingWatermarkIcon,
  Brightness1Icon,
  Brightness2Icon,
  Brightness3Icon,
  Brightness4Icon,
  Brightness5Icon,
  Brightness6Icon,
  Brightness7Icon,
  BrightnessAutoIcon,
  BrightnessHighIcon,
  BrightnessLowIcon,
  BrightnessMediumIcon,
  BrokenImageIcon,
  BrushIcon,
  BubbleChartIcon,
  BugReportIcon,
  BuildIcon,
  BurstModeIcon,
  BusinessIcon,
  BusinessCenterIcon,
  CachedIcon,
  CakeIcon,
  CallIcon,
  CallEndIcon,
  CallMadeIcon,
  CallMergeIcon,
  CallMissedIcon,
  CallMissedOutgoingIcon,
  CallReceivedIcon,
  CallSplitIcon,
  CallToActionIcon,
  CameraIcon,
  CameraAltIcon,
  CameraFrontIcon,
  CameraRearIcon,
  CameraRollIcon,
  CancelIcon,
  CardGiftcardIcon,
  CardMembershipIcon,
  CardTravelIcon,
  CasinoIcon,
  CastIcon,
  CastConnectedIcon,
  CenterFocusStrongIcon,
  CenterFocusWeakIcon,
  ChangeHistoryIcon,
  ChatIcon,
  ChatBubbleIcon,
  ChatBubbleOutlineIcon,
  CheckIcon,
  CheckBoxIcon,
  CheckBoxOutlineBlankIcon,
  CheckCircleIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChildCareIcon,
  ChildFriendlyIcon,
  ChromeReaderModeIcon,
  ClassIcon,
  ClearIcon,
  ClearAllIcon,
  CloseIcon,
  ClosedCaptionIcon,
  CloudIcon,
  CloudCircleIcon,
  CloudDoneIcon,
  CloudDownloadIcon,
  CloudOffIcon,
  CloudQueueIcon,
  CloudUploadIcon,
  CodeIcon,
  CollectionsIcon,
  ColorLensIcon,
  ColorizeIcon,
  CommentIcon,
  CompareIcon,
  CompareArrowsIcon,
  ComputerIcon,
  ConfirmationNumberIcon,
  ContactMailIcon,
  ContactPhoneIcon,
  ContactsIcon,
  ContentCopyIcon,
  ContentCutIcon,
  ContentPasteIcon,
  ControlPointIcon,
  ControlPointDuplicateIcon,
  CopyrightIcon,
  CreateIcon,
  CreateNewFolderIcon,
  CreditCardIcon,
  CropIcon,
  Crop169Icon,
  Crop32Icon,
  Crop54Icon,
  Crop75Icon,
  CropDinIcon,
  CropFreeIcon,
  CropLandscapeIcon,
  CropOriginalIcon,
  CropPortraitIcon,
  CropRotateIcon,
  CropSquareIcon,
  DashboardIcon,
  DataUsageIcon,
  DateRangeIcon,
  DehazeIcon,
  DeleteIcon,
  DeleteForeverIcon,
  DeleteSweepIcon,
  DescriptionIcon,
  DesktopMacIcon,
  DesktopWindowsIcon,
  DetailsIcon,
  DeveloperBoardIcon,
  DeveloperModeIcon,
  DevicesIcon,
  DevicesOtherIcon,
  DialerSipIcon,
  DialpadIcon,
  DirectionsIcon,
  DirectionsBikeIcon,
  DirectionsBoatIcon,
  DirectionsBusIcon,
  DirectionsCarIcon,
  DirectionsRailwayIcon,
  DirectionsRunIcon,
  DirectionsSubwayIcon,
  DirectionsTransitIcon,
  DirectionsWalkIcon,
  DiscFullIcon,
  DnsIcon,
  DoNotDisturbIcon,
  DoNotDisturbAltIcon,
  DoNotDisturbOffIcon,
  DoNotDisturbOnIcon,
  DockIcon,
  DomainIcon,
  DoneIcon,
  DoneAllIcon,
  DonutLargeIcon,
  DonutSmallIcon,
  DraftsIcon,
  DragHandleIcon,
  DriveEtaIcon,
  DvrIcon,
  EditIcon,
  EditLocationIcon,
  EmailIcon,
  EnhancedEncryptionIcon,
  EqualizerIcon,
  ErrorIcon,
  ErrorOutlineIcon,
  EuroSymbolIcon,
  EvStationIcon,
  EventIcon,
  EventAvailableIcon,
  EventBusyIcon,
  EventNoteIcon,
  EventSeatIcon,
  ExitToAppIcon,
  ExpandLessIcon,
  ExpandMoreIcon,
  ExplicitIcon,
  ExploreIcon,
  ExposureIcon,
  ExposureNeg1Icon,
  ExposureNeg2Icon,
  ExposurePlus1Icon,
  ExposurePlus2Icon,
  ExposureZeroIcon,
  ExtensionIcon,
  FaceIcon,
  FastForwardIcon,
  FastRewindIcon,
  FavoriteIcon,
  FavoriteBorderIcon,
  FeaturedPlayListIcon,
  FeaturedVideoIcon,
  FeedbackIcon,
  FiberDvrIcon,
  FiberManualRecordIcon,
  FiberNewIcon,
  FiberPinIcon,
  FiberSmartRecordIcon,
  FileDownloadIcon,
  FileUploadIcon,
  FilterIcon,
  Filter1Icon,
  Filter2Icon,
  Filter3Icon,
  Filter4Icon,
  Filter5Icon,
  Filter6Icon,
  Filter7Icon,
  Filter8Icon,
  Filter9Icon,
  Filter9PlusIcon,
  FilterBAndWIcon,
  FilterCenterFocusIcon,
  FilterDramaIcon,
  FilterFramesIcon,
  FilterHdrIcon,
  FilterListIcon,
  FilterNoneIcon,
  FilterTiltShiftIcon,
  FilterVintageIcon,
  FindInPageIcon,
  FindReplaceIcon,
  FingerprintIcon,
  FirstPageIcon,
  FitnessCenterIcon,
  FlagIcon,
  FlareIcon,
  FlashAutoIcon,
  FlashOffIcon,
  FlashOnIcon,
  FlightIcon,
  FlightLandIcon,
  FlightTakeoffIcon,
  FlipIcon,
  FlipToBackIcon,
  FlipToFrontIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderSharedIcon,
  FolderSpecialIcon,
  FormatAlignCenterIcon,
  FormatAlignJustifyIcon,
  FormatAlignLeftIcon,
  FormatAlignRightIcon,
  FormatBoldIcon,
  FormatClearIcon,
  FormatColorFillIcon,
  FormatColorResetIcon,
  FormatColorTextIcon,
  FormatIndentDecreaseIcon,
  FormatIndentIncreaseIcon,
  FormatItal48PxIcon,
  FormatLineSpacingIcon,
  FormatListBulletedIcon,
  FormatListNumberedIcon,
  FormatPaintIcon,
  FormatQuoteIcon,
  FormatShapesIcon,
  FormatSizeIcon,
  FormatStrikethroughIcon,
  FormatTextdirectionLToRIcon,
  FormatTextdirectionRToLIcon,
  FormatUnderlinedIcon,
  ForumIcon,
  ForwardIcon,
  Forward10Icon,
  Forward30Icon,
  Forward5Icon,
  FreeBreakfastIcon,
  FullscreenIcon,
  FullscreenExitIcon,
  FunctionsIcon,
  GTranslateIcon,
  GamepadIcon,
  GamesIcon,
  GavelIcon,
  GestureIcon,
  GetAppIcon,
  GolfCourseIcon,
  GpsFixedIcon,
  GpsNotFixedIcon,
  GpsOffIcon,
  GradeIcon,
  GradientIcon,
  GrainIcon,
  GrapheqIcon,
  GridOffIcon,
  GridOnIcon,
  GroupIcon,
  GroupAddIcon,
  GroupWorkIcon,
  HdrOffIcon,
  HdrOnIcon,
  HdrStrongIcon,
  HdrWeakIcon,
  HeadsetIcon,
  HeadsetM48PxIcon,
  HealingIcon,
  HearingIcon,
  HelpIcon,
  HighQualityIcon,
  HighlightIcon,
  HighlightOffIcon,
  HistoryIcon,
  HomeIcon,
  HotTubIcon,
  HotelIcon,
  HourglassEmptyIcon,
  HourglassFullIcon,
  HttpIcon,
  HttpsIcon,
  ImageIcon,
  ImageAspectRatioIcon,
  ImportContactsIcon,
  ImportExportIcon,
  ImportantDevicesIcon,
  InboxIcon,
  InfoIcon,
  InfoOutlineIcon,
  InputIcon,
  InsertChartIcon,
  InsertCommentIcon,
  InsertDriveFileIcon,
  InsertEmoticonIcon,
  InsertInvitationIcon,
  InsertLinkIcon,
  InsertPhotoIcon,
  InvertColorsIcon,
  InvertColorsOffIcon,
  IsoIcon,
  KeyboardIcon,
  KeyboardArrowDownIcon,
  KeyboardArrowLeftIcon,
  KeyboardArrowRightIcon,
  KeyboardArrowUpIcon,
  KeyboardBackspaceIcon,
  KeyboardCapslockIcon,
  KeyboardHideIcon,
  KeyboardReturnIcon,
  KeyboardTabIcon,
  KeyboardVoiceIcon,
  KitchenIcon,
  LabelIcon,
  LabelOutlineIcon,
  LandscapeIcon,
  LanguageIcon,
  LaptopIcon,
  LaptopChromebookIcon,
  LaptopMacIcon,
  LaptopWindowsIcon,
  LastPageIcon,
  LaunchIcon,
  LayersIcon,
  LayersClearIcon,
  LeakAddIcon,
  LeakRemoveIcon,
  LensIcon,
  LibraryAddIcon,
  LibraryBooksIcon,
  LibraryMus48PxIcon,
  LightbulbOutlineIcon,
  LineStyleIcon,
  LineWeightIcon,
  LinearScaleIcon,
  LinkIcon,
  LinkedCameraIcon,
  ListIcon,
  LiveHelpIcon,
  LiveTvIcon,
  LocalActivityIcon,
  LocalAirportIcon,
  LocalAtmIcon,
  LocalBarIcon,
  LocalCafeIcon,
  LocalCarWashIcon,
  LocalConvenienceStoreIcon,
  LocalDiningIcon,
  LocalDrinkIcon,
  LocalFloristIcon,
  LocalGasStationIcon,
  LocalGroceryStoreIcon,
  LocalHospitalIcon,
  LocalHotelIcon,
  LocalLaundryServiceIcon,
  LocalLibraryIcon,
  LocalMallIcon,
  LocalMoviesIcon,
  LocalOfferIcon,
  LocalParkingIcon,
  LocalPharmacyIcon,
  LocalPhoneIcon,
  LocalPizzaIcon,
  LocalPlayIcon,
  LocalPostOfficeIcon,
  LocalPrintshopIcon,
  LocalSeeIcon,
  LocalShippingIcon,
  LocalTaxiIcon,
  LocationCityIcon,
  LocationDisabledIcon,
  LocationOffIcon,
  LocationOnIcon,
  LocationSearchingIcon,
  LockIcon,
  LockOpenIcon,
  LockOutlineIcon,
  LooksIcon,
  Looks3Icon,
  Looks4Icon,
  Looks5Icon,
  Looks6Icon,
  LooksOneIcon,
  LooksTwoIcon,
  LoopIcon,
  LoupeIcon,
  LowPriorityIcon,
  LoyaltyIcon,
  M48PxIcon,
  MailIcon,
  MailOutlineIcon,
  MapIcon,
  MarkunreadIcon,
  MarkunreadMailboxIcon,
  MemoryIcon,
  MenuIcon,
  MergeTypeIcon,
  MessageIcon,
  MmsIcon,
  MnoneIcon,
  ModeCommentIcon,
  ModeEditIcon,
  MoffIcon,
  MonetizationOnIcon,
  MonochromePhotosIcon,
  MoodIcon,
  MoodBadIcon,
  MoreIcon,
  MoreHorizIcon,
  MoreVertIcon,
  MotorcycleIcon,
  MouseIcon,
  MoveToInboxIcon,
  MovieIcon,
  MovieCreationIcon,
  MovieFilterIcon,
  MultilineChartIcon,
  MusnoteIcon,
  MusvideoIcon,
  MyLocationIcon,
  NatureIcon,
  NaturePeopleIcon,
  NavigateBeforeIcon,
  NavigateNextIcon,
  NavigationIcon,
  NearMeIcon,
  NetworkCellIcon,
  NetworkCheckIcon,
  NetworkLockedIcon,
  NetworkWifiIcon,
  NewReleasesIcon,
  NextWeekIcon,
  NfcIcon,
  NoEncryptionIcon,
  NoSimIcon,
  NotInterestedIcon,
  NoteIcon,
  NoteAddIcon,
  NotificationsIcon,
  NotificationsActiveIcon,
  NotificationsNoneIcon,
  NotificationsOffIcon,
  NotificationsPausedIcon,
  OndemandVideoIcon,
  OpacityIcon,
  OpenInBrowserIcon,
  OpenInNewIcon,
  OpenWithIcon,
  PagesIcon,
  PageviewIcon,
  PaletteIcon,
  PanToolIcon,
  PanoramaIcon,
  PanoramaFishEyeIcon,
  PanoramaHorizontalIcon,
  PanoramaVerticalIcon,
  PanoramaWideAngleIcon,
  PartyModeIcon,
  PauseIcon,
  PauseCircleFilledIcon,
  PauseCircleOutlineIcon,
  PaymentIcon,
  PeopleIcon,
  PeopleOutlineIcon,
  PermCameraM48PxIcon,
  PermContactCalendarIcon,
  PermDataSettingIcon,
  PermDeviceInformationIcon,
  PermIdentityIcon,
  PermMediaIcon,
  PermPhoneMsgIcon,
  PermScanWifiIcon,
  PersonIcon,
  PersonAddIcon,
  PersonOutlineIcon,
  PersonPinIcon,
  PersonPinCircleIcon,
  PersonalVideoIcon,
  PetsIcon,
  PhoneIcon,
  PhoneAndroidIcon,
  PhoneBluetoothSpeakerIcon,
  PhoneForwardedIcon,
  PhoneInTalkIcon,
  PhoneIphoneIcon,
  PhoneLockedIcon,
  PhoneMissedIcon,
  PhonePausedIcon,
  PhonelinkIcon,
  PhonelinkOffIcon,
  PhotoIcon,
  PhotoAlbumIcon,
  PhotoCameraIcon,
  PhotoFilterIcon,
  PhotoLibraryIcon,
  PictureAsPdfIcon,
  PictureInPictureIcon,
  PictureInPictureAltIcon,
  PieChartIcon,
  PieChartOutlinedIcon,
  PinDropIcon,
  PlaceIcon,
  PlayArrowIcon,
  PlayCircleFilledIcon,
  PlayCircleFilledWhiteIcon,
  PlayCircleOutlineIcon,
  PlayForWorkIcon,
  PlaylistAddIcon,
  PlaylistAddCheckIcon,
  PlaylistPlayIcon,
  PlusOneIcon,
  PollIcon,
  PolymerIcon,
  PoolIcon,
  PortableWifiOffIcon,
  PortraitIcon,
  PowerIcon,
  PowerInputIcon,
  PowerSettingsNewIcon,
  PregnantWomanIcon,
  PresentToAllIcon,
  PrintIcon,
  PriorityHighIcon,
  Publ48PxIcon,
  PublishIcon,
  QueryBuilderIcon,
  QuestionAnswerIcon,
  QueueIcon,
  QueueMus48PxIcon,
  QueuePlayNextIcon,
  RadioIcon,
  RadioButtonCheckedIcon,
  RadioButtonUncheckedIcon,
  RateReviewIcon,
  ReceiptIcon,
  RecentActorsIcon,
  RecordVoiceOverIcon,
  RedeemIcon,
  RedoIcon,
  RefreshIcon,
  RemoveIcon,
  RemoveCircleIcon,
  RemoveCircleOutlineIcon,
  RemoveFromQueueIcon,
  RemoveRedEyeIcon,
  RemoveShoppingCartIcon,
  RepeatIcon,
  RepeatOneIcon,
  ReplayIcon,
  Replay10Icon,
  Replay30Icon,
  Replay5Icon,
  ReplyIcon,
  ReplyAllIcon,
  ReportIcon,
  ReportProblemIcon,
  RestaurantIcon,
  RestaurantMenuIcon,
  RestoreIcon,
  RestorePageIcon,
  RingVolumeIcon,
  RoomIcon,
  RoomServiceIcon,
  Rotate90DegreesCcwIcon,
  RotateLeftIcon,
  RotateRightIcon,
  RoundedCornerIcon,
  RouterIcon,
  RowingIcon,
  RssFeedIcon,
  RvHookupIcon,
  SatelliteIcon,
  SaveIcon,
  ScannerIcon,
  ScheduleIcon,
  SchoolIcon,
  ScreenLockLandscapeIcon,
  ScreenLockPortraitIcon,
  ScreenLockRotationIcon,
  ScreenRotationIcon,
  ScreenShareIcon,
  SdCardIcon,
  SdStorageIcon,
  SearchIcon,
  SecurityIcon,
  SelectAllIcon,
  SendIcon,
  SentimentDissatisfiedIcon,
  SentimentNeutralIcon,
  SentimentSatisfiedIcon,
  SentimentVeryDissatisfiedIcon,
  SentimentVerySatisfiedIcon,
  SettingsIcon,
  SettingsApplicationsIcon,
  SettingsBackupRestoreIcon,
  SettingsBluetoothIcon,
  SettingsBrightnessIcon,
  SettingsCellIcon,
  SettingsEthernetIcon,
  SettingsInputAntennaIcon,
  SettingsInputComponentIcon,
  SettingsInputCompositeIcon,
  SettingsInputHdmiIcon,
  SettingsInputSvideoIcon,
  SettingsOverscanIcon,
  SettingsPhoneIcon,
  SettingsPowerIcon,
  SettingsRemoteIcon,
  SettingsSystemDaydreamIcon,
  SettingsVoiceIcon,
  ShareIcon,
  ShopIcon,
  ShopTwoIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  ShortTextIcon,
  ShowChartIcon,
  ShuffleIcon,
  SignalCellular0BarIcon,
  SignalCellular1BarIcon,
  SignalCellular2BarIcon,
  SignalCellular3BarIcon,
  SignalCellular4BarIcon,
  SignalCellularConnectedNoInternet0BarIcon,
  SignalCellularConnectedNoInternet1BarIcon,
  SignalCellularConnectedNoInternet2BarIcon,
  SignalCellularConnectedNoInternet3BarIcon,
  SignalCellularConnectedNoInternet4BarIcon,
  SignalCellularNoSimIcon,
  SignalCellularNullIcon,
  SignalCellularOffIcon,
  SignalWifi0BarIcon,
  SignalWifi1BarIcon,
  SignalWifi1BarLockIcon,
  SignalWifi2BarIcon,
  SignalWifi2BarLockIcon,
  SignalWifi3BarIcon,
  SignalWifi3BarLockIcon,
  SignalWifi4BarIcon,
  SignalWifi4BarLockIcon,
  SignalWifiOffIcon,
  SimCardIcon,
  SimCardAlertIcon,
  SkipNextIcon,
  SkipPreviousIcon,
  SlideshowIcon,
  SlowMotionVideoIcon,
  SmartphoneIcon,
  SmokeFreeIcon,
  SmokingRoomsIcon,
  SmsIcon,
  SmsFailedIcon,
  SnoozeIcon,
  SortIcon,
  SpaIcon,
  SpaceBarIcon,
  SpeakerIcon,
  SpeakerGroupIcon,
  SpeakerNotesIcon,
  SpeakerNotesOffIcon,
  SpeakerPhoneIcon,
  SpellcheckIcon,
  StarHalfIcon,
  StarsIcon,
  StayCurrentLandscapeIcon,
  StayCurrentPortraitIcon,
  StayPrimaryLandscapeIcon,
  StayPrimaryPortraitIcon,
  StopIcon,
  StopScreenShareIcon,
  StorageIcon,
  StoreIcon,
  StoreMallDirectoryIcon,
  StraightenIcon,
  StreetviewIcon,
  StrikethroughSIcon,
  StyleIcon,
  SubdirectoryArrowLeftIcon,
  SubdirectoryArrowRightIcon,
  SubjectIcon,
  SubscriptionsIcon,
  SubtitlesIcon,
  SubwayIcon,
  SupervisorAccountIcon,
  SurroundSoundIcon,
  SwapCallsIcon,
  SwapHorizIcon,
  SwapVertIcon,
  SwapVerticalCircleIcon,
  SwitchCameraIcon,
  SwitchVideoIcon,
  SyncIcon,
  SyncDisabledIcon,
  SyncProblemIcon,
  SystemUpdateIcon,
  SystemUpdateAltIcon,
  TabIcon,
  TabUnselectedIcon,
  TabletIcon,
  TabletAndroidIcon,
  TabletMacIcon,
  TagFacesIcon,
  TapAndPlayIcon,
  TerrainIcon,
  TextFieldsIcon,
  TextFormatIcon,
  TextsmsIcon,
  TextureIcon,
  TheatersIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  ThumbsUpDownIcon,
  TimeToLeaveIcon,
  TimelapseIcon,
  TimelineIcon,
  TimerIcon,
  Timer10Icon,
  Timer3Icon,
  TimerOffIcon,
  TitleIcon,
  TocIcon,
  TodayIcon,
  TollIcon,
  TonalityIcon,
  TouchAppIcon,
  ToysIcon,
  TrackChangesIcon,
  Traff48PxIcon,
  TrainIcon,
  TramIcon,
  TransferWithinAStationIcon,
  TransformIcon,
  TranslateIcon,
  TrendingDownIcon,
  TrendingFlatIcon,
  TrendingUpIcon,
  TuneIcon,
  TurnedInIcon,
  TurnedInNotIcon,
  TvIcon,
  UnarchiveIcon,
  UndoIcon,
  UnfoldLessIcon,
  UnfoldMoreIcon,
  UpdateIcon,
  UsbIcon,
  VerifiedUserIcon,
  VerticalAlignBottomIcon,
  VerticalAlignCenterIcon,
  VerticalAlignTopIcon,
  VibrationIcon,
  VideoCallIcon,
  VideoLabelIcon,
  VideoLibraryIcon,
  VideocamIcon,
  VideocamOffIcon,
  VideogameAssetIcon,
  ViewAgendaIcon,
  ViewArrayIcon,
  ViewCarouselIcon,
  ViewColumnIcon,
  ViewComfyIcon,
  ViewCompactIcon,
  ViewDayIcon,
  ViewHeadlineIcon,
  ViewListIcon,
  ViewModuleIcon,
  ViewQuiltIcon,
  ViewStreamIcon,
  ViewWeekIcon,
  VisibilityIcon,
  VisibilityOffIcon,
  VoiceChatIcon,
  VoicemailIcon,
  VolumeDownIcon,
  VolumeMuteIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  VpnKeyIcon,
  VpnLockIcon,
  WallpaperIcon,
  WarningIcon,
  WatchIcon,
  WatchLaterIcon,
  WbAutoIcon,
  WbCloudyIcon,
  WbIncandescentIcon,
  WbIridescentIcon,
  WbSunnyIcon,
  WcIcon,
  WebIcon,
  WebAssetIcon,
  WeekendIcon,
  WhatshotIcon,
  WidgetsIcon,
  WifiIcon,
  WifiLockIcon,
  WifiTetheringIcon,
  WorkIcon,
  WrapTextIcon,
  YoutubeSearchedForIcon,
  ZoomOutMapIcon
};
